dist: xenial

language: python

python:
  - "3.5"
  - "3.6"

install: 
  - "pip install --upgrade pip"
  # Uninstall preinstalled pip packages, so that subsequent pip install works
  # correctly (resolver breaks otherwise, as versions are different)
  # https://docs.travis-ci.com/user/reference/trusty/#pre-installed-pip-packages
  - "pip freeze | xargs pip uninstall -y"
  - "pip install --use-feature=2020-resolver --upgrade -e .[test]"
  # Install translate toolkit to get pocount binary
  - sudo apt-get install translate-toolkit

script:
  - "DJANGO_SETTINGS_MODULE=cove.settings py.test -n 2 cove --cov --cov-report="
  # Check that strings have Spanish translation (for cove-ocds)
  - "python manage.py makemessages -l es"
  - "[ \"$TRAVIS_PULL_REQUEST\" = \"false\" ] || [ \"`pocount --incomplete cove/locale/es/LC_MESSAGES/django.po`\" = \"\" ]"

