name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
        django-version:
          - "Django==4.2.4"
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64


      - run: "pip install --upgrade pip"
      - run: "pip install --upgrade -e .[test]"
      - run: "pip install '${{ matrix.django-version }}'"


      - run: "pip install Django==4.2.3"
      - run: "pip install certifi==2023.5.7"
      - run: "pip install exceptiongroup==1.1.2"
      - run: "pip install flake8==6.0.0"
      - run: "pip install hypothesis==6.81.1"
      - run: "pip install ijson==3.2.2"
      - run: "pip install jsonschema==4.18.3"
      - run: "pip install jsonschema-specifications==2023.6.1"
      - run: "pip install numpy==1.25.1"
      - run: "pip install pycodestyle==2.10.0"
      - run: "pip install pyflakes==3.0.1"
      - run: "pip install pytest-localserver==0.7.1"
      - run: "pip install referencing==0.29.1"
      - run: "pip install rpds-py==0.8.10"
      - run: "pip install selenium==4.10.0"
      - run: "pip install werkzeug==2.3.6"
      - run: "pip install zodb==5.8.0"

      - run: find cove
      - run: grep -r cove_tags cove/
      - name: Check existing migrations can run and no migrations are missing
        env:
          DJANGO_SETTINGS_MODULE: cove.settings
          DATABASE_URL: postgresql://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres
        shell: bash
        run: |
          ./manage.py migrate
          ./manage.py makemigrations --check --dry-run
          ./manage.py check --fail-level WARNING
          
          
          
          


      - run: "py.test -n 2 cove --cov"
        env:
          DJANGO_SETTINGS_MODULE: cove.settings
          SECRET_KEY: 7ur)dt+e%1^e6$8_sd-@1h67_5zixe2&39%r2$$8_7v6fr_7ee
        if: ${{ matrix.django-version != 'Django>=4.2,<4.3' }}
      # Don't set PYTHONWARNING for Django 4.2, as that has some known
      # deprecation warnings for 5.0
      - run: "py.test -n 2 cove --cov"
        env:
          DJANGO_SETTINGS_MODULE: cove.settings
          SECRET_KEY: 7ur)dt+e%1^e6$8_sd-@1h67_5zixe2&39%r2$$8_7v6fr_7ee
        if: ${{ matrix.django-version == 'Django>=4.2,<4.3' }}




      - run: "sudo apt-get update"
      - run: "sudo apt-get install gettext"
      # Check that changes to .po files have been compiled
      - run: "python manage.py compilemessages"
      - run: "git diff --exit-code"
      # Install translate toolkit to get pocount binary
      - run: "sudo apt-get install translate-toolkit"
      # Check that strings have Spanish translation (for cove-ocds)
      - run: "python manage.py makemessages -l es"
      - run: "[ \"`pocount --incomplete cove/locale/es/LC_MESSAGES/django.po`\" = \"\" ]"
        if: github.event_name == 'pull_request'
