name: Lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install
      run: pip install --use-feature=2020-resolver --upgrade -e .[test]

    - name: Install Black & iSort
      run: pip install black isort

    - name: Isort
      run: isort --check-only --recursive *.py */

    - name: Flake8
      run: flake8

    - name: Black
      run: black --check *.py */
